apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flex-alerts
  namespace: flex
  labels:
    team: flex
spec:
  groups:
    - name: flex-alerts
      rules:
      - alert: flex-app-nede
        expr: kube_deployment_status_replicas_available{namespace="flex"} == 0
        for: 3m
        annotations:
          consequence: "`{{ $labels.deployment }}` er nede"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-restart
        expr: sum(increase(kube_pod_container_status_restarts_total{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"}[5m])) by (container, pod) > 2
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` sin container `{{ $labels.container }}` har restartet mye"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-not-ready
        expr: count(kube_pod_container_status_ready{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"} == 0) by (container, pod) > 0
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` sin container `{{ $labels.container }}` er ikke ready"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-mangler-metrikker
        expr: count(up{team="flex"} offset 1h) by (app) unless count(up{team="flex"}) by (app)
        for: 5m
        annotations:
          consequence: "`{{ $labels.app }}` har sluttet å rapportere metrikker"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-error-logging
        expr: (sum(rate(log_messages_errors{namespace="flex", app!="cloudsql-proxy", app!="elector", app!="linkerd-proxy", app!="wonderwall", app!="linkerd-init", level="Error"}[1m])) by (app) / sum(rate(log_messages_total{namespace="flex", app!="cloudsql-proxy", app!="elector", app!="linkerd-proxy", app!="wonderwall", app!="linkerd-init"}[1m])) by (app)) > 0.1
        for: 3m
        annotations:
          consequence: "`{{ $labels.app }}` 1 av 10 loggmeldinger er error"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-cpu
        expr: (sum(rate(container_cpu_usage_seconds_total{namespace="flex",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="POD",container!="",container!="sykepengesoknad-sak-status-metrikk"}[2m])) by (pod) / sum(kube_pod_container_resource_requests{namespace="flex",resource="cpu",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="POD",container!="",container!="sykepengesoknad-sak-status-metrikk"}) by (pod)) > 1
        for: 5m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer cpu enn den har requestet"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-ram
        expr: (sum(kube_pod_container_resource_requests{namespace="flex", resource="memory",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="POD",container!=""}) by (pod) - sum(container_memory_working_set_bytes{namespace="flex",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="POD", container!=""}) by (pod)) < 0
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer ram enn den har requestet"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-http-4xx
        expr: (sum(rate(response_total{namespace="flex", status_code=~"^4\\d\\d"}[3m])) by (app) / sum(rate(response_total{namespace="flex", status_code=~"^2\\d\\d"}[3m])) by (app)) > 0.01
        for: 3m
        annotations:
          consequence: "`{{ $labels.app }}` har mange HTTP 4xx-feilresponser"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-http-5xx
        expr: (sum(rate(response_total{namespace="flex", status_code=~"^5\\d\\d"}[3m])) by (app) / sum(rate(response_total{namespace="flex", status_code=~"^2\\d\\d"}[3m])) by (app)) > 0.01
        for: 3m
        annotations:
          consequence: "`{{ $labels.app }}` har mange HTTP 5xx-feilresponser"
        labels:
          namespace: flex
          severity: critical
