apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: flex-alerts
  namespace: default
  labels:
    team: flex
spec:
  receivers:
    slack:
      channel: '#spøkelser'
      #prependText: '<!here> | '
  alerts:
    - alert: flex-app-nede
      expr: sum(up{team="flex"}) by (app) == 0
      for: 4m
      description: "{{ $labels.app }} er nede"
      action: "Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: flex-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"}[30m])) by (container) > 2
      for: 1m
      description: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
      action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: flex-not-ready
      expr: sum(kube_pod_container_status_ready{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"} == 0) by (container) > 0
      for: 10m
      description: "{{ $labels.container }} svarer ikke ok på readiness de siste 10 minutter"
      action: "Se `kubectl describe pod {{ $labels.pod_name }} -n flex` for events, og `kubectl logs {{ $labels.pod_name }} -c {{ $labels.app }} -n flex` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: flex-errorlogging
      expr: (100 * sum by (log_app) (rate(logd_messages_total{log_team="flex",log_app!="elector",log_level="Error"}[5m])) / sum by (log_app) (rate(logd_messages_total{log_team="flex",log_app!="elector"}[5m]))) > 10
      for: 3m
      description: "{{ $labels.log_app }} rapporterer error i loggene"
      action: "Sjekk loggene til {{ $labels.log_app }}, for å se hvorfor det er så mye feil (over 10 feil per 100 logger de siste 5 minuttene)"
