apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flex-alerts
  namespace: flex
  labels:
    team: flex
spec:
  groups:
    - name: flex-alerts
      rules:
      - alert: flex-app-nede
        expr: kube_deployment_status_replicas_available{namespace="flex"} == 0
        for: 1m
        annotations:
          consequence: "`{{ $labels.deployment }}` er nede"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-restart
        expr: sum(increase(kube_pod_container_status_restarts_total{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"}[5m])) by (container, pod) > 2
        for: 1m
        annotations:
          consequence: "`{{ $labels.pod }}` sin container `{{ $labels.container }}` har restartet mye"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-not-ready
        expr: count(kube_pod_container_status_ready{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"} == 0) by (container, pod) > 0
        for: 1m
        annotations:
          consequence: "`{{ $labels.pod }}` sin container `{{ $labels.container }}` er ikke ready"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-mangler-metrikker
        expr: count(up{team="flex"} offset 1h) by (app) unless count(up{team="flex"}) by (app)
        for: 5m
        annotations:
          consequence: "`{{ $labels.app }}` har sluttet å rapportere metrikker"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-error-logging
        expr: ((sum(rate(logd_messages_total{log_team="flex",log_app!="elector",log_level="Error"}[5m])) by (log_app)) / (sum(rate(logd_messages_total{log_team="flex",log_app!="elector"}[5m])) by (log_app))) > 0.1
        for: 1m
        annotations:
          consequence: "`{{ $labels.log_app }}` 1 av 10 loggmeldinger er error"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-cpu
        expr: (sum(rate(container_cpu_usage_seconds_total{namespace="flex",container!="linkerd-proxy",container!="cloudsql-proxy",container!="POD",container!=""}[5m])) by (pod) / sum(kube_pod_container_resource_limits{namespace="flex",resource="cpu", container!="linkerd-proxy",container!="cloudsql-proxy"}) by (pod)) > 0.90
        for: 1m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer enn 90% cpu"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-ram
        expr: sum(kube_pod_container_resource_requests{namespace="flex", resource="memory", container!="linkerd-proxy",container!="cloudsql-proxy"}) by (pod) - sum(container_memory_working_set_bytes{namespace="flex",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="POD", container!=""}) by (pod) < 0
        for: 1m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer ram enn den har requestet"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-http-4xx
        expr: (sum(rate(response_total{namespace="flex", app!="flex-sykepengesoknad-pdfgen", status_code=~"^4\\d\\d"}[3m])) by (app) / sum(rate(response_total{namespace="flex", status_code=~"^2\\d\\d"}[3m])) by (app)) > 0.01
        for: 1m
        annotations:
          consequence: "`{{ $labels.app }}` har mange HTTP 4xx-feilresponser"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-http-5xx
        expr: (sum(rate(response_total{namespace="flex", status_code=~"^5\\d\\d"}[3m])) by (app) / sum(rate(response_total{namespace="flex", status_code=~"^2\\d\\d"}[3m])) by (app)) > 0.01
        for: 1m
        annotations:
          consequence: "`{{ $labels.app }}` har mange HTTP 5xx-feilresponser"
        labels:
          namespace: flex
          severity: critical
