apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flex-alerts
  namespace: flex
  labels:
    team: flex
spec:
  groups:
    - name: flex-alerts
      rules:
      - alert: flex-app-nede
        expr: sum(up{team="flex"}) by (app) == 0
        for: 1m
        annotations:
          consequence: Application is unavailable
          action: "`kubectl get pod | grep <app>`"
          summary: Alle podder til appen er nede
        labels:
          namespace: flex
          severity: critical
