apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flex-alerts
  namespace: flex
  labels:
    team: flex
spec:
  groups:
    - name: flex-alerts
      rules:
      - alert: flex-app-nede
        expr: kube_deployment_status_replicas_available{namespace="flex"} == 0
        for: 3m
        annotations:
          consequence: "`{{ $labels.deployment }}` er nede"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-restart
        expr: sum(increase(kube_pod_container_status_restarts_total{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"}[5m])) by (container, pod) > 2
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` sin container `{{ $labels.container }}` har restartet mye"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-not-ready
        expr: count(kube_pod_container_status_ready{namespace="flex", container!="elector", container!="flex-datafortelling", container!="flex-datafortelling-run-on-deploy", container!="flex-bigquery-soda", container!="flex-bigquery-soda-run-on-deploy", container!="flex-slack-metrikker", container!="flex-slack-metrikker-run-on-deploy", container!="cloudsql-proxy", container!="linkerd-proxy"} == 0) by (container, pod) > 0
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` sin container `{{ $labels.container }}` er ikke ready"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-mangler-metrikker
        expr: count(up{team="flex"} offset 1h) by (app) unless count(up{team="flex"}) by (app)
        for: 5m
        annotations:
          consequence: "`{{ $labels.app }}` har sluttet å rapportere metrikker"
        labels:
          namespace: flex
          severity: critical
      - alert: flex-error-logging
        expr: (sum(rate(log_messages_errors{namespace="flex", app!="cloudsql-proxy", app!="elector", app!="linkerd-proxy", app!="wonderwall", app!="linkerd-init", level="Error"}[2m])) by (app) / sum(rate(log_messages_total{namespace="flex", app!="cloudsql-proxy", app!="elector", app!="linkerd-proxy", app!="wonderwall", app!="linkerd-init"}[2m])) by (app)) > 0.1
        for: 3m
        annotations:
          consequence: "`{{ $labels.app }}` 1 av 10 loggmeldinger er error"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-cpu
        expr: (sum(rate(container_cpu_usage_seconds_total{namespace="flex",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="wonderwall",container!="POD",container!=""}[2m])) by (pod) / sum(kube_pod_container_resource_requests{namespace="flex",resource="cpu",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="wonderwall",container!="POD",container!=""}) by (pod)) > 1
        for: 5m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer cpu enn den har requestet"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-ram-request
        expr: (sum(kube_pod_container_resource_requests{namespace="flex", resource="memory",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="wonderwall",container!="POD",container!=""}) by (pod) - sum(container_memory_working_set_bytes{namespace="flex",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="wonderwall",container!="POD", container!=""}) by (pod)) < 0
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer minne enn den har requestet"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-app-ram-limit
        expr: (sum(container_memory_working_set_bytes{namespace="flex",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="wonderwall",container!="POD", container!=""}) by (pod) / sum(kube_pod_container_resource_limits{namespace="flex", resource="memory",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="elector",container!="wonderwall",container!="POD",container!=""}) by (pod)) > 0.95
        for: 3m
        annotations:
          consequence: "`{{ $labels.pod }}` bruker mer enn 95% av minne limit"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-spring-http-4xx
        expr: (sum(rate(http_server_requests_seconds_count{namespace="flex", status=~"^4\\d\\d", uri!="/internal/health/**", uri!="/internal/health", uri!="/internal/prometheus"}[10m])) by (app,uri) / sum(rate(http_server_requests_seconds_count{namespace="flex", status=~"^2\\d\\d", uri!="/internal/health/**", uri!="/internal/health", uri!="/internal/prometheus"}[10m])) by (app,uri)) > 0.1
        for: 3m
        annotations:
          consequence: "`{{ $labels.app }}` har mer enn 10% HTTP 4xx-feilresponser for uri {{ $labels.uri }}"
        labels:
          namespace: flex
          severity: warning
      - alert: flex-spring-http-5xx
        expr: (sum(rate(http_server_requests_seconds_count{namespace="flex", status=~"^5\\d\\d", uri!="/internal/health/**", uri!="/internal/health", uri!="/internal/prometheus"}[10m])) by (app,uri) / sum(rate(http_server_requests_seconds_count{namespace="flex", status=~"^2\\d\\d", uri!="/internal/health/**", uri!="/internal/health", uri!="/internal/prometheus"}[10m])) by (app,uri)) > 0.1
        for: 3m
        annotations:
          consequence: "`{{ $labels.app }}` har mer enn 10% HTTP 5xx-feilresponser for uri {{ $labels.uri }}"
        labels:
          namespace: flex
          severity: critical
