apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flex-alerts
  namespace: flex
  labels:
    team: flex
spec:
  groups:
    - name: flex-alerts
      rules:
      - alert: flex-app-nede
        expr: sum(up{team="flex"}) by (app) == 0
        for: 1m
        annotations:
          consequence: Application is unavailable
          action: "`kubectl get pod | grep <app>`"
          summary: Alle podder til appen er nede
        labels:
          namespace: flex
          severity: critical
      - alert: flex-restart
        expr: sum(increase(kube_pod_container_status_restarts_total{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"}[30m])) by (container) > 2
        for: 1m
        annotations:
          consequence: Application is restarting
          action: "`kubectl get pod"
          summary: En av containerene i podden restarter
        labels:
          namespace: flex
          severity: critical
      - alert: flex-not-ready
        expr: count(kube_pod_container_status_ready{namespace="flex", container!="elector", container!="cloudsql-proxy", container!="linkerd-proxy"} == 0) by (container) > 0
        for: 1m
        annotations:
          consequence: Application is not ready
          action: "`kubectl get pod"
          summary: En av containerene i podden er ikke ready
        labels:
          namespace: flex
          severity: critical
