apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: spoknad-alerts-sbs
  labels:
    team: SPoknad
spec:
  receivers:
    slack:
      channel: '#spøkelser'
      #prependText: '<!here> | '
  alerts:
    - alert: spoknad-sbs-app-nede
      expr: up{app=~"syfoapi|sykepengesoknad|sykefravaer|modiasyfofront",job="kubernetes-pods"} == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: spoknad-sbs-mangler-metrikker
      expr: absent(up{app=~"syfoapi|sykepengesoknad|sykefravaer|modiasyfofront",job="kubernetes-pods"})
      for: 5m
      description: "{{ $labels.app }} rapporterer ingen metrikker i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk om {{ $labels.app }} i {{ $labels.kubernetes_namespace }} er oppe"
      sla: respond within 1h, during office hours
      severity: danger
