name: Deploy flex-alert to NAIS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Apply alerts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        containers: [ prod-gcp, prod-fss, dev-gcp, dev-fss ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to cluster
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.containers }}
          RESOURCE: flex-alerts.yaml
