name: Deploy flex-alert to NAIS
on:
  push:
    branches:
      - master
jobs:
  deploy_prod_fss:
    name: Deploy alert to prod-fss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Call deployment-cli/action and apply yaml file to prod-fss
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-fss
          team: flex
          rawresources: flex-alerts.yaml
  deploy_prod_sbs:
    name: Deploy alert to prod-sbs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Call deployment-cli/action and apply yaml file to prod-sbs
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-sbs
          team: flex
          rawresources: flex-alerts-sbs.yaml
