name: Deploy spoknad-alert to NAIS
on:
  push:
    branches:
      - master
jobs:
  deploy_prod_fss:
    name: Deploy alert til prod-fss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Call deployment-cli/action and apply yaml file to prod-fss
        uses: navikt/deployment-cli/action@0edb199
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-fss
          team: SPoknad
          rawresources: spoknad-alerts.yaml
  deploy_prod_sbs:
    name: Deploy alert til prod-sbs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Call deployment-cli/action and apply yaml file to prod-sbs
        uses: navikt/deployment-cli/action@0edb199
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-sbs
          team: SPoknad
          rawresources: spoknad-alerts-sbs.yaml
