name: Deploy flex-alert to NAIS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Apply alerts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [ prod-gcp, prod-fss, dev-gcp, dev-fss ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to cluster
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.containers }}
          RESOURCE: flex-alerts-new.yaml
